### ISSUE TITLE
没有/vendor/autoload.php文件

### ISSUE THREAD

**Issue by Merrrrrr** [juzeon/fast-mail-bomber#1]
PHP Warning:  require_once(fast-mail-bomber-master/vendor/autoload.php): failed to open stream: No such file or directory in fast-mail-bomber-master/init.php on line 2
PHP Fatal error:  require_once(): Failed opening required 'fast-mail-bomber-master/vendor/autoload.php' (include_path='.:/usr/share/php') in fast-mail-bomber-master/init.php on line 2

**Comment by juzeon** [comment]
Please install dependencies manually using composer according to the document.
